"""The analyst console: serve the case files, the diagnostics and the cost ledger.

    python -m src.ui.app --cases cases_fixture          # then open http://127.0.0.1:8000
    python -m src.ui.app --cases cases                  # the real run

WHAT THE UI IS FOR. Two audiences, and they want different things. A judge wants to see that the
investigation is real - that the evidence came from somewhere nameable, that the recommendation
changed when new evidence arrived, that the uncertainty is quantified rather than asserted. An
analyst wants to work the queue: what needs attention, what does policy allow me to do, and what
will happen if I approve it. The page serves the first by making the second honest.

DELIBERATELY THIN. Three endpoints and a static file. Everything the page shows already exists on
disk because the investigation wrote it - the answer files, the diagnostics sidecar, the run
manifest. The server does no analysis of its own, so there is no second implementation of the
investigation that could disagree with the first, and nothing here can make the case files look
better than they are.

The approval endpoint is a stub that records a decision to a local file. Blocking a real card is
not in scope; the brief says these actions may be simulated. What is NOT simulated is which
actions were allowed to be executed without a human - that comes from the policy engine's route
table, and the page shows the route on every action.
"""
from __future__ import annotations

import argparse
import json
import os
from datetime import datetime, timezone

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
HERE = os.path.dirname(os.path.abspath(__file__))
CONSOLE = os.path.join(HERE, "console.html")


def read_cases(cases_dir: str) -> dict:
    """Everything the page needs, assembled from what the investigation left on disk."""
    path = cases_dir if os.path.isabs(cases_dir) else os.path.join(ROOT, cases_dir)
    payload: dict = {"cases": {}, "diagnostics": {}, "manifest": None, "banner": ""}
    if not os.path.isdir(path):
        payload["banner"] = (f"{cases_dir}/ does not exist yet - run the investigation first: "
                             f"python -m src.agent.run --data data_fixture --out cases_fixture")
        return payload

    for name in sorted(os.listdir(path)):
        if not name.endswith(".json") or name.startswith("_"):
            continue
        with open(os.path.join(path, name), encoding="utf-8") as fh:
            obj = json.load(fh)
        payload["cases"][obj.get("case_id", name)] = obj

    for key, fname in (("diagnostics", "_diagnostics.json"), ("manifest", "_run_manifest.json")):
        fpath = os.path.join(path, fname)
        if os.path.exists(fpath):
            with open(fpath, encoding="utf-8") as fh:
                payload[key] = json.load(fh)

    # Say plainly when the numbers on screen came from the synthetic fixture. A console that
    # shows made-up cases without saying so is the one thing this page must never do.
    if "fixture" in os.path.basename(path):
        payload["banner"] = ("Synthetic fixture data - generated by src/fixtures/generate.py, not "
                             "the organizers' dataset. Shapes are planted, so nothing here is a "
                             "finding about the real cases.")
    return payload


def build_app(cases_dir: str):
    from fastapi import FastAPI, HTTPException
    from fastapi.responses import FileResponse, JSONResponse

    app = FastAPI(title="Fraud Case Register", docs_url=None, redoc_url=None)

    @app.get("/")
    def console():
        return FileResponse(CONSOLE, media_type="text/html")

    @app.get("/api/cases")
    def api_cases():
        return JSONResponse(read_cases(cases_dir))

    @app.get("/api/cases/{case_id}")
    def api_case(case_id: str):
        data = read_cases(cases_dir)
        if case_id not in data["cases"]:
            raise HTTPException(404, f"no answer file for {case_id}")
        return JSONResponse({"case": data["cases"][case_id],
                             "diagnostics": (data["diagnostics"] or {}).get(case_id)})

    @app.post("/api/approve/{case_id}")
    def api_approve(case_id: str, action: str = "", decision: str = "approved",
                    approver: str = "analyst"):
        """Record a human decision on an action the policy engine routed to L1 or L2.

        Appends to `approvals.jsonl` and does nothing else - no card is blocked, no message is
        sent. The value is the audit trail: who approved what, when, and on which case. The
        brief permits these actions to be simulated; it does not permit pretending a human
        approved something they did not.
        """
        path = os.path.join(ROOT, "approvals.jsonl")
        record = {"case_id": case_id, "action": action, "decision": decision,
                  "approver": approver,
                  "at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")}
        with open(path, "a", encoding="utf-8") as fh:
            fh.write(json.dumps(record) + "\n")
        return JSONResponse({"recorded": record, "log": os.path.relpath(path, ROOT)})

    return app


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--cases", default="cases_fixture",
                    help="directory of answer files to serve (cases or cases_fixture)")
    ap.add_argument("--host", default="127.0.0.1")
    ap.add_argument("--port", type=int, default=8000)
    a = ap.parse_args()

    data = read_cases(a.cases)
    print(f"serving {len(data['cases'])} case(s) from {a.cases}/")
    if data["banner"]:
        print(f"  note: {data['banner']}")
    print(f"  http://{a.host}:{a.port}")

    import uvicorn
    uvicorn.run(build_app(a.cases), host=a.host, port=a.port, log_level="warning")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
